name: Build and deploy Jekyll site to GCS
on:
  push:
    branches:
    - master

env:
  GCS_BUCKET: ${{ secrets.GCS_BUCKET }}

jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build
      uses:  lemonarc/jekyll-action@1.0.0
    - name: Setup - gcloud / gsutil
      uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        service_account_key: ${{ secrets.GCS_SA_KEY }}
        project_id: ${{ secrets.GCS_PROJECT }}
        export_default_credentials: true
    - name: Deploy
      run: |-
        gsutil -m rsync -R _site gs://$GCS_BUCKET
